version: "3"
services:
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
     - 5432:5432
  metabase:
    image: metabase/metabase:v0.32.0
    depends_on:
      - postgres
      - mb-postgres
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=${MB_POSTGRES_PASSWORD}
      - MB_DB_HOST=mb-postgres
  mb-postgres:
    image: postgres:10.1-alpine
    volumes:
    - ./docker/mb-postgres/data:/var/lib/postgresql/data:rw
    environment:
    - POSTGRES_PASSWORD=${MB_POSTGRES_PASSWORD}
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
     - 6543:5432
